parameters:
#    acmemarket.example.class: Acme\marketBundle\Example

services:
#    acmemarket.example:
#        class: %acmemarket.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
