Acme\marketBundle\Entity\Brand:
    type: entity
    table: Brand
    fields:
        idbrand:
            id: true
            type: integer
            unsigned: true
            nullable: false
            column: idBrand
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        description:
            type: text
            nullable: true
        dateupdated:
            type: datetime
            nullable: true
            column: dateUpdated
        datecreated:
            type: datetime
            nullable: true
            column: dateCreated
    lifecycleCallbacks: {  }
