Acme\marketBundle\Entity\Measure:
    type: entity
    table: Measure
    fields:
        idmeasure:
            id: true
            type: integer
            unsigned: true
            nullable: false
            column: idMeasure
        datemeasure:
            type: datetime
            nullable: false
            column: dateMeasure
        value:
            type: float
            nullable: false
        dateupdated:
            type: datetime
            nullable: true
            column: dateUpdated
        datecreated:
            type: datetime
            nullable: true
            column: dateCreated
    oneToOne:
        brandbrand:
            targetEntity: Brand
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Brand_idBrand:
                    referencedColumnName: idBrand
            orphanRemoval: false
        towntown:
            targetEntity: Town
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Town_idTown:
                    referencedColumnName: idTown
            orphanRemoval: false
    lifecycleCallbacks: {  }
