Acme\marketBundle\Entity\Town:
    type: entity
    table: Town
    fields:
        idtown:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idTown
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        dateupdated:
            type: datetime
            nullable: true
            column: dateUpdated
        datecreated:
            type: datetime
            nullable: true
            column: dateCreated
    lifecycleCallbacks: {  }
